apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laslo-app-ingress
  namespace: laslo
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: vote.laslo.diogohack.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: laslo-svc-vote
                port:
                  number: 80
    - host: result.laslo.diogohack.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: laslo-svc-result
                port:
                  number: 80
