---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laslo-deployment-worker
  namespace: laslo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: scolas3/worker:latest
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: laslo-worker-sec
                  value: REDIS_HOST
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: laslo-worker-sec
                  value: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: laslo-worker-sec
                  value: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laslo-worker-sec
                  value: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: laslo-worker-sec
                  value: DB_NAME
