name: CI/CD to EKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write # for OIDC
  contents: read # for clone repo

jobs:
  
  detect-changes: # checks whether one of the microservices have been changed
    runs-on: ubuntu-latest
    outputs:
      vote: ${{ steps.filter.outputs.vote }}
      worker: ${{ steps.filter.outputs.worker }}
      result: ${{ steps.filter.outputs.result }}

    steps:
      - name: DEBUG ARN
        run: echo ${{ secrets.AWS_ROLE_TO_BE_ASSUMED_CICD }}
      - name: Print GitHub OIDC sub
        shell: bash
        run: echo "SUB CLAIM: repo:${{ github.repository }}:*"

      - uses: actions/checkout@v3

      - name: Detect changes for each service
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            vote:
              - 'vote/**'
            worker:
              - 'worker/**'
            result:
              - 'result/**'

  build-and-push:
    needs: detect-changes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT_TOKEN }}

      - name: Build & push vote
        if: needs.detect-changes.outputs.vote == 'true'
        run: |
          docker build -t scolas3/vote:${GITHUB_SHA} ./vote
          docker push scolas3/vote:${GITHUB_SHA}

      - name: Build & push worker
        if: needs.detect-changes.outputs.worker == 'true'
        run: |
          docker build -t scolas3/worker:${GITHUB_SHA} ./worker
          docker push scolas3/worker:${GITHUB_SHA}

      - name: Build & push result
        if: needs.detect-changes.outputs.result == 'true'
        run: |
          docker build -t scolas3/result:${GITHUB_SHA} ./result
          docker push scolas3/result:${GITHUB_SHA}

  deploy:
    needs: [detect-changes, build-and-push]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC) # assumes a pre set up role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_BE_ASSUMED_CICD }}
          aws-region: ${{ vars.AWS_EKS_REGION }}
          audience: sts.amazonaws.com

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name ${{ vars.AWS_EKS_NAME }} \
            --region ${{ vars.AWS_EKS_REGION }}

      # Update Deployments only when changed
      - name: Update vote deployment
        if: needs.detect-changes.outputs.vote == 'true'
        run: |
          kubectl set image deployment/laslo-deployment-vote \
            vote=scolas3/vote:${GITHUB_SHA} \
            -n laslo
          kubectl rollout status deployment/vote-deployment -n laslo

      - name: Update worker deployment
        if: needs.detect-changes.outputs.worker == 'true'
        run: |
          kubectl set image deployment/laslo-deployment-worker \
            worker=scolas3/worker:${GITHUB_SHA} \
            -n laslo
          kubectl rollout status deployment/worker-deployment -n laslo

      - name: Update result deployment
        if: needs.detect-changes.outputs.result == 'true'
        run: |
          kubectl set image deployment/laslo-deployment-result \
            result=scolas3/result:${GITHUB_SHA} \
            -n laslo
          kubectl rollout status deployment/result-deployment -n laslo
